### ISSUE TITLE
Update create-react-app fork

### ISSUE THREAD

**Issue by osmarpetry** [rio-cloud/create-react-app#17]
### Is your proposal related to a problem?

`create-react-app` fork should be up to date

### Describe the solution you'd like

Update the fork, I already did this there: [https://github.com/osmarpetry/create-react-app](https://github.com/osmarpetry/create-react-app)

### Describe alternatives you've considered

Some other contributor can do this alone too

### Additional context

(Write your answer here.)

**Comment by ritters** [comment]
Sorry for the late response.
Indeed we do try to update it regularly. The latest time we do it is when create-react-app releases a new version. 
Did you experience any inconvenience by using our fork because we did not update?
